[package]
name = "victoria3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
fltk = "1.3.20"
glob = "0.3.0"
image = "0.24.5"
zip = "0.6.3"
